import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd]

src = [
    'model_net1.c',
    'sub_0000_net1_command_stream.c',
    'sub_0000_net1_invoke.c',
    'sub_0000_net1_model_data.c',
    'sub_0000_net1_tensors.c',
]

objs = DefineGroup('Models', src, depend = [], CPPPATH = CPPPATH)

Return('objs')
